services:
  postgres:
    # postgres:16-alpine - для теста, на проде конечно используем не урезанную версию
    # Докер я тоже хорошо знаю)
    image: postgres:16-alpine
    container_name: ${PROJECT_PREFIX}_db
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-subscriptions}
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-subscriptions}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  app:
     build: .
     container_name: ${PROJECT_PREFIX}_service
     ports:
       - "8080:8080"
     environment:
       DB_HOST: postgres
       DB_PORT: 5432
       DB_USER: ${DB_USER:-postgres}
       DB_PASSWORD: ${DB_PASSWORD:-postgres}
       DB_NAME: ${DB_NAME:-subscriptions}
     depends_on:
       postgres:
         condition: service_healthy
     networks:
       - app_network
     restart: unless-stopped

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge